### PR TITLE
Update pre-commit config file

### PR DESCRIPTION
**Pull request by sadikkuzu**
* Change `flake` repo url
  * from gitlab to github
* Run `pre-commit autoupdate`

### CODE REVIEW

**Comment by nilsnolde** [comment]
thanks! 

just realizing I was not very smart when setting up GHA.. @sadikkuzu would you mind updating the workflow yaml as well so your PR runs? I think this is better in the top section:
```
name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md
```

**Comment by sadikkuzu** [comment]
My pleasure 🙏🏼 

Sure, I'll handle in that way.

**Comment by sadikkuzu** [comment]
I think this line
https://github.com/gis-ops/routing-py/blob/e5c976acd4759b5c4b24d910e3516f15afd96d33/.github/workflows/ci-tests.yml#L65
should be changed with
```sh
pre-commit run --all-files
```

Because, `pre-commit run` acts only on files in staging area.
So in this workflow there is "no files to check" message.
image

**Comment by nilsnolde** [comment]
jep of course, you're right! if you wanna do it while you're at it, feel free. thanks for pointing it out!

**Comment by nilsnolde** [comment]
Oops looks like a lot of files never ran black.. thanks, looks good!

**Review by nilsnolde — APPROVED** [review]

**Pull request merged**
